### ISSUE TITLE
proxy wont work with twitter website

### ISSUE THREAD

**Issue by erfantkerfan** [sameersbn/docker-squid#71]
I set up a proxy in docker with everything as default like this:
```
Squid:
  image: sameersbn/squid:3.5.27-2
  ports:
    - "3128:3128"
  volumes:
    - ./cache:/var/spool/squid
    - ./squid.conf:/etc/squid/squid.conf
  restart: always
```
also, I have just changed these settings:
```
http_access allow all
dns_v4_first on
```
